### ISSUE TITLE
CRuby の Head(3.1.0dev) で rspec-expectations の CI がコケる

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#106]
なんか自分のが落ちててやべっと思ったら https://github.com/rspec/rspec-expectations/runs/2736238907

https://github.com/rspec/rspec-expectations/runs/2758116219 他の人のも落ちてるっぽい。

```
============= Starting rubocop ===============
bin/rubocop lib
wrong number of arguments (given 5, expected 1)
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/psych.rb:322:in `safe_load'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:179:in `yaml_safe_load'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:152:in `load_yaml_configuration'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:35:in `load_file'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/config_loader.rb:79:in `configuration_from_file'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/config_store.rb:44:in `for'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:171:in `apply_default_formatter'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/lib/rubocop/cli.rb:37:in `run'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/bin/rubocop:13:in `block in <top (required)>'
/home/runner/.rubies/ruby-head/lib/ruby/3.1.0/benchmark.rb:311:in `realtime'
/home/runner/work/rspec-expectations/rspec-expectations/bundle/ruby/3.1.0/gems/rubocop-0.52.1/bin/rubocop:12:in `<top (required)>'
/home/runner/work/rspec-expectations/rspec-expectations/bin/rubocop:14:in `load'
/home/runner/work/rspec-expectations/rspec-expectations/bin/rubocop:14:in `<main>'
```

rspec も rubocop も psych も全部メジャーなプロジェクトだし、どうせどっかで誰かが動いてくれてるんだろう、ゆっくり待とうかというお気持ち・・・(ボーイスカウト精神に欠ける人間性)

**Comment by kachick** [comment]
https://github.com/ruby/ruby/commit/9137caaf457d65bc4c4c05cc0d6e5d6740f669f1

はぁ、ついこないだ psych を 4系に上げて、それが原因という感じなのかな

https://github.com/ruby/psych/commits/master

見てみても、CIがコケまくりでなにがなんだかわからない。

でも、錚々たるメンバーがアクティブに関わってくださってるので、多分すぐに・・・

**Comment by kachick** [comment]
https://github.com/ruby/psych/pull/493
https://github.com/ruby/psych/pull/487

このへんかなー？

これ、どっちかというと rspec-expectations が 依存している rubocop の version が古すぎたりする方が問題だったりするのかな `rubocop-0.52.1` って・・・

https://github.com/rspec/rspec-expectations/blob/040d1b0bba83031c9ae432fd3a4462fdd1cc74e7/Gemfile#L91-L93

rspec は ruby 1.8.7 とかサポート対象にしているから、そうせざるを得なかったりするんだろうか。辛そう。

**Comment by kachick** [comment]
案外さくっと update できたりしないかな？と思ってトライしてみたがボロボロ落ちた。namespaceのprefixみたいなのついてない古いスタイルにはwarningが出て、 cop 名が変わったり分割されてたりはエラーになる。とりあえずエラーを直すのに単純置換で良いのかと思ったら

https://github.com/rspec/rspec-expectations/blob/040d1b0bba83031c9ae432fd3a4462fdd1cc74e7/.rubocop_rspec_base.yml#L1-L5

```yaml
# This file was generated on 2021-04-23T09:17:30+01:00 from the rspec-dev repo.
# DO NOT modify it by hand as your changes will get lost the next time it is generated.

# This file contains defaults for RSpec projects. Individual projects
# can customize by inheriting this file and overriding particular settings.
```

ということで、直接いじるな系っぽい。
なんかだいぶ昔に rspec-dev ちょっと触ったことはあるんだけど全く覚えてない。

https://github.com/rspec/rspec-dev

の中を軽く見たが、どこで generate しているのやらわからず

**Comment by kachick** [comment]
```console
~/repos/rspec-dev main
❯ bin/rake setup
Cloning into 'rspec'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'rspec-core'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'rspec-expectations'...
remote: Enumerating objects: 21407, done.
remote: Counting objects: 100% (366/366), done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 21407 (delta 196), reused 250 (delta 148), pack-reused 21041
Receiving objects: 100% (21407/21407), 5.25 MiB | 4.88 MiB/s, done.
Resolving deltas: 100% (12039/12039), done.
Cloning into 'rspec-mocks'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'rspec-rails'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'rspec-support'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - /Users/kachick/repos/rspec-dev/repos/rspec
/Users/kachick/repos/rspec-dev/Rakefile:37:in `block in run_command'
/Users/kachick/repos/rspec-dev/Rakefile:34:in `each'
/Users/kachick/repos/rspec-dev/Rakefile:34:in `run_command'
/Users/kachick/repos/rspec-dev/Rakefile:284:in `block (2 levels) in <top (required)>'
/Users/kachick/repos/rspec-dev/vendor/bundle/ruby/3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => setup => bundle:install
(See full trace by running task with --trace)
```

🙌

**Comment by kachick** [comment]
なんかもう流石にどっかで直ったんだろうけどあんま追う気力がわかないのでclose

**Comment by kachick** [comment]
https://secret-garden.hatenablog.com/entry/2021/05/23/200803
https://bugs.ruby-lang.org/issues/17866

このあたりかも？
