### ISSUE TITLE
`Rake::TestTask.new(:test)` & `bundle exec rake test` での 失敗時、backtrace に bundler 関連の path が含まれてノイズになるのを消し込む方法

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#98]
## TL;DR

* `bundle exec rake test --suppress-backtrace='\/bundle'`

## 何についてか / About

https://github.com/kachick/ruby-ulid/issues/119
https://stackoverflow.com/questions/5053566/how-do-i-suppress-the-huge-stack-trace-after-a-rake-testtask-failure
https://gist.github.com/coldnebo/1003628

#33 に書いたように、個人的には test-unit で書けるところは test-unit で済ませたい。もっと refine された test-unit 的な物があればそれは乗り換えてもいいと思うが、 rspec は rspec 周辺ツールの多機能さみたいなところがどうしても必要でないなら基本的に避けたい。
が、一つ annoy な事がある。

`bundle exec rake spec` とかで、 it の中で raise するとこうなる。これはよろしい。

```plaintext
Finished in 0.04484 seconds (files took 0.33422 seconds to load)
7 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/own_spec.rb:30 # RSpec::Matchers::PowerAssertMatchers be_assert shows power assert reports if the block returns falsy

/Users/kachick/.rubies/ruby-3.0.1/bin/ruby -w -I/Users/kachick/repos/rspec-matchers-power_assert_matchers/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.10.1/lib:/Users/kachick/repos/rspec-matchers-power_assert_matchers/vendor/bundle/ruby/3.0.0/gems/rspec-support-3.10.2/lib /Users/kachick/repos/rspec-matchers-power_assert_matchers/vendor/bundle/ruby/3.0.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

`bundle exec rake test` とかで、 test_fooobar の中で raise するとこうなる。これはうざったい。

```plaintext
Finished in 0.002754 seconds.
----------------------------------------------------------------------------------------------------------------------------------------
2 tests, 8 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
50% passed                                                                                                                              ----------------------------------------------------------------------------------------------------------------------------------------726.22 tests/s, 2904.87 assertions/s                                                                                                    rake aborted!
Command failed with status (1)
/Users/kachick/repos/abb/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `load'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/kachick/.gem/ruby/3.0.1/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
/Users/kachick/.gem/ruby/3.0.1/bin/bundle:23:in `load'
/Users/kachick/.gem/ruby/3.0.1/bin/bundle:23:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by kachick** [comment]
そもそも 思考停止で `Rake::TestTask.new(:test)` を使ってきたのだけれど、本当にそれが良いのだろうか？

https://github.com/test-unit/test-unit/blob/9e8a0048317c677fa1d0a7e3245d6c18502c26a7/doc/text/how-to.md

見ても全くrake task紹介されていないし、直接なら使えるオプションが一杯有り

```console
$ bundle exec ruby ./test/**/test_*.rb
Loaded suite ./test/test_abb
Started
E
========================================================================================================================================
Error: test_abb(TestAbb): RuntimeError:
./test/test_abb.rb:25:in `test_abb'
     22:     assert_raises(ArgumentError) do
     23:       Abb.fold(:google)
     24:     end
  => 25:     raise
     26:   end
     27:
     28:   def test_refinements
========================================================================================================================================
.
Finished in 0.003876 seconds.
----------------------------------------------------------------------------------------------------------------------------------------
2 tests, 8 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
----------------------------------------------------------------------------------------------------------------------------------------
516.00 tests/s, 2063.98 assertions/s
```

こっちの方が良くないか・・・？

**Comment by kachick** [comment]
https://github.com/ruby/rake/blob/fc688bd8cd6b4178178a0d7bb31068122ba25943/lib/rake/testtask.rb

https://github.com/rspec/rspec-core/blob/247d0a706ffa955718d600f3588aeb1e60cebde4/lib/rspec/core/rake_task.rb

要は鼓に2つを見比べれば分かる話か？ 👀

**Comment by kachick** [comment]
答えを得た気がする。

https://github.com/ruby/rake/blob/fc688bd8cd6b4178178a0d7bb31068122ba25943/lib/rake/application.rb#L558-L564

```ruby
          ["--suppress-backtrace PATTERN",
            "Suppress backtrace lines matching regexp PATTERN. " +
            "Ignored if --trace is on.",
            lambda { |value|
              options.suppress_backtrace_pattern = Regexp.new(value)
            }
          ],
```

ということで

```shell
bundle exec rake test --suppress-backtrace='\/bundle'
```

これで抹殺できた。
勿論自分のコードの中にたまたま `bundle` が含まれたりしてたときに使えるような厳密なものでは無いと思うが、自分の場合は十分そうだ。
